apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-servlet
  namespace: test
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: simple-servlet
        image: appdkonrad/simple-servlet:without-agent
        ports:
        - containerPort: 8080
